"""add publisher to book

Revision ID: 76e21236e0af
Revises: 856e0eb9cff6
Create Date: 2025-09-20 14:53:25.696016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e21236e0af'
down_revision: Union[str, Sequence[str], None] = '856e0eb9cff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('publisher', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Books', 'publisher')
    # ### end Alembic commands ###
